theme = "catppuccin_frappe_translate"

[editor]
auto-format = false
# auto-reload = true
# auto-info = true
undercurl = true
bufferline = "multiple"
color-modes = true
cursorcolumn = true
cursorline = true
idle-timeout = 40
line-number = "relative"
mouse = true
true-color = true
end-of-line-diagnostics = "hint"
insert-final-newline = true
# rainbow-brackets = true
shell = ["nu", "--stdin", "-c"]
default-line-ending = "native"

# [editor.word-completion]
# enable = true
# trigger-length = 4

# [editor.version-control]
# inline-blame = true

# [editor.inline-blame]
# show = "cursor-line"

[editor.statusline]
# center = ["file-modification-indicator", "file-name"]
# left = ["mode", "spinner", "version-control", "read-only-indicator"]
# right = [
#   "diagnostics",
#   "selections",
#   "position",
#   "total-line-numbers",
#   "file-encoding",
#   "file-indent-style",
#   "file-line-ending",
#   "file-type",
# ]
# separator = "â¸½"
left = [
  "mode",
  "spinner",
  "version-control",
  "read-only-indicator",
  "file-name",
  "file-modification-indicator",
]
center = ["diagnostics", "workspace-diagnostics"]
right = [
  "register",
  "position",
  "primary-selection-length",
  "selections",
  "file-encoding",
  "file-indent-style",
  "file-line-ending",
  "position-percentage",
  "file-type",
  "spacer",
]
diagnostics = ["hint", "info", "warning", "error"]
workspace-diagnostics = ["hint", "info", "warning", "error"]
# separator = "â”‚"

[editor.statusline.mode]
insert = "INSERT"
normal = "NORMAL"
select = "SELECT"

# [editor.explorer]
# position = "center"
# column-width = 22

[editor.lsp]
auto-signature-help = true
display-inlay-hints = true
display-messages = true
display-signature-help-docs = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
nbsp = "â£"
newline = "â"
space = "Â·"
tab = "â‡¥"
tabpad = "-"  # Tabs will look like "â†’Â·Â·Â·" (depending on tab width)

[editor.soft-wrap]
enable = true

[editor.auto-save]
after-delay.enable = true

[editor.indent-guides]
render = true
character = "â•" # Some characters that work well: "â–", "â”†", "â”Š", "â¸½"
skip-levels = 1
# rainbow-indent = "dim"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[icons.vcs]
enabled = true
icon = "âŒ¬"

[icons.kind]
enabled = true
number = "ï“·"
string = "î­¾"
function = "ó°Š•"
color = "ó°Œ"

[icons.fs]
enabled = true
php = { glyph = "îŸ²", color = "#1976D2" }
godot = { glyph = "î™Ÿ", color = "#2196F3" }
gd = { glyph = "î™Ÿ", color = "#2196F3" }
gdshader = { glyph = "ó°˜·", color = "#9C27B0" }
wgsl = { glyph = "î½’", color = "#E06C75" }
wesl = { glyph = "îº°", color = "#E06C75" }
cj = "î»±"
yml = "îš¨"
yaml = "îš¨"
conf = "î˜•"
kdl = "ï€“"
Makefile = "î™³"
ron = "ó°”˜"
db = "îœ†"
sql = "ó°†¼"
jsonc = "î˜‹"
json5 = "î ‹"
"ignore" = "ó°ˆ‰"
".ignore" = "ó°ˆ‰"
"lrc" = "ó°¨–"
"env" = ""
"hurl" = { glyph = "î‰º", color = "#DE3163" }
directory = "ğŸ–¿"

[icons.ui.statusline]
separator = "â¸½"

[icons.diagnostic]
error = '!'
warning = 'â–²'
info = 'â—'
hint = 'â—‹'

[icons.ui.virtual]
ruler = "|"

[keys.normal]
"A-down" = [
  "extend_line_below",
  "delete_selection",
  "paste_after",
  "collapse_selection",
]
"A-j" = [
  "extend_line_below",
  "delete_selection",
  "paste_after",
  "collapse_selection",
]
"A-k" = [
  "extend_line_below",
  "delete_selection",
  "move_visual_line_up",
  "paste_before",
  "collapse_selection",
]
"A-up" = [
  "extend_line_below",
  "delete_selection",
  "move_visual_line_up",
  "paste_before",
  "collapse_selection",
]

# G = "goto_last_line"
C-s = ":write"

tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

"\\" = ":reflow"        # |
X = "extend_line_above"

# [keys.normal.z]
# o = [":toggle soft-wrap.wrap-at-text-width"]

[keys.normal.space]
x = ":buffer-close"
n = "signature_help"

[keys.normal.space.w]
r = ":reload"
c = ":config-reload"

[keys.insert]
S-tab = "move_parent_node_start"

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
